ALTER TABLE "Order"
  ADD COLUMN "governorate" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "block" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "street" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "building" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "floorOrApartment" TEXT,
  ADD COLUMN "deliveryInstructions" TEXT;

ALTER TABLE "Order" ALTER COLUMN "governorate" DROP DEFAULT;
ALTER TABLE "Order" ALTER COLUMN "block" DROP DEFAULT;
ALTER TABLE "Order" ALTER COLUMN "street" DROP DEFAULT;
ALTER TABLE "Order" ALTER COLUMN "building" DROP DEFAULT;
