export type Product={id:string;name:string;nameAr:string;description:string;price:number;category:string;rating:number;reviews:number;image:string;tags:string[];best?:boolean;seasonal?:boolean;gift?:boolean;servings?:string;allergens?:string[]};
export const img=(id:string,w=900,h=700)=>`https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format&q=82`;
export const money=(v:number)=>`KWD ${v.toFixed(3)}`;
export const categories=[
{id:'cakes',name:'Cakes',nameAr:'الكيكات',description:'Layered cakes crafted for every occasion',image:img('1578985545062-69928b1d9587'),count:18},{id:'pastries',name:'Pastries',nameAr:'المعجنات',description:'Buttery baked goods fresh each morning',image:img('1555507036-ab1f4038808a'),count:12},{id:'cheesecakes',name:'Cheesecakes',nameAr:'تشيز كيك',description:'Creamy, indulgent in every flavor',image:img('1565958011703-44f9829ba187'),count:8},{id:'oriental',name:'Oriental Sweets',nameAr:'حلويات شرقية',description:'Traditional Gulf sweets, modern twist',image:img('1603532648955-039310d9ed75'),count:10},{id:'tarts',name:'Tarts & Slices',nameAr:'تارت وشرائح',description:'Elegant tarts with seasonal fruits',image:img('1464305795204-6f5bbfc7fb81'),count:9},{id:'cookies',name:'Cookies',nameAr:'بسكويت',description:'Handcrafted cookies baked fresh daily',image:img('1499636136210-6f4ee915583e'),count:11},{id:'giftboxes',name:'Gift Boxes',nameAr:'صناديق الهدايا',description:'Curated boxes for gifting occasions',image:img('1549465220-1a8b9238cd48'),count:6},{id:'seasonal',name:'Seasonal',nameAr:'موسمي',description:'Limited edition seasonal collections',image:img('1558326567-98ae2405596b'),count:7}];
export const products:Product[]=[
{id:'chocolate-truffle-cake',name:'Chocolate Truffle Cake',nameAr:'كيكة تروفل الشوكولاتة',description:'Rich dark chocolate layers with silky truffle ganache, Belgian chocolate curls and edible gold leaf.',price:8.5,category:'cakes',rating:5,reviews:284,image:img('1578985545062-69928b1d9587'),tags:['Best Seller','Signature'],best:true,servings:'8–10 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'lotus-cheesecake',name:'Lotus Cheesecake',nameAr:'تشيز كيك اللوتس',description:'Creamy New York-style cheesecake on a buttery Lotus biscuit base.',price:6.5,category:'cheesecakes',rating:4.8,reviews:198,image:img('1565958011703-44f9829ba187'),tags:['Best Seller'],best:true,servings:'8–10 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'pistachio-rose-kunafa',name:'Pistachio Rose Kunafa',nameAr:'كنافة الفستق والورد',description:'Fine kunafa threads with pistachio cream, rose water syrup and crushed pistachios.',price:5,category:'oriental',rating:4.9,reviews:156,image:img('1603532648955-039310d9ed75'),tags:['New','Seasonal'],seasonal:true,servings:'6–8 servings',allergens:['Gluten','Nuts','Dairy']},
{id:'vanilla-bean-cake',name:'Vanilla Bean Cake',nameAr:'كيكة الفانيلا',description:'Light vanilla sponge with Madagascar vanilla bean cream and fresh berries.',price:7,category:'cakes',rating:4.7,reviews:142,image:img('1542826438-bd32f3d81bbc'),tags:['Signature'],servings:'8–10 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'caramel-croissant',name:'Salted Caramel Croissant',nameAr:'كرواسان الكراميل المملح',description:'Buttery laminated croissant filled with house-made salted caramel cream.',price:1.5,category:'pastries',rating:4.9,reviews:312,image:img('1555507036-ab1f4038808a'),tags:['Daily Fresh'],best:true,servings:'1 piece',allergens:['Gluten','Dairy','Eggs']},
{id:'cinnamon-roll',name:'Classic Cinnamon Roll',nameAr:'رول القرفة',description:'Soft cinnamon rolls with signature cream cheese frosting.',price:2,category:'pastries',rating:4.8,reviews:228,image:img('1616198814651-e71f960c3180'),tags:['Morning Fresh'],servings:'1 piece',allergens:['Gluten','Dairy','Eggs']},
{id:'red-velvet-cake',name:'Red Velvet Dream',nameAr:'كيكة المخمل الأحمر',description:'Classic red velvet layers with velvety cream cheese frosting.',price:8,category:'cakes',rating:4.8,reviews:189,image:img('1551529834-525807d6b4f3'),tags:['Classic'],servings:'8–10 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'mango-passion-tart',name:'Mango Passion Tart',nameAr:'تارت المانجو والباشن',description:'Buttery pastry shell with passionfruit curd and fresh mango.',price:4.5,category:'tarts',rating:4.7,reviews:87,image:img('1464305795204-6f5bbfc7fb81'),tags:['Seasonal','Limited'],seasonal:true,servings:'6–8 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'biscoff-tiramisu',name:'Biscoff Tiramisu',nameAr:'تيراميسو البسكويت',description:'Coffee-soaked ladyfingers with mascarpone cream and Biscoff crumble.',price:6,category:'cakes',rating:4.9,reviews:134,image:img('1571877227200-a0d98ea607e9'),tags:['New','Signature'],servings:'6–8 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'date-tahini-cookies',name:'Date & Tahini Cookies',nameAr:'بسكويت التمر والطحينة',description:'Medjool dates, tahini and sesame in a soft-baked cookie.',price:3.5,category:'cookies',rating:4.8,reviews:176,image:img('1499636136210-6f4ee915583e'),tags:['Local','Signature'],best:true,servings:'12 cookies',allergens:['Gluten','Sesame','Nuts']},
{id:'matcha-white-chocolate',name:'Matcha White Choc Cake',nameAr:'كيكة الماتشا والشوكولاتة البيضاء',description:'Ceremonial matcha layers with white chocolate ganache.',price:7.5,category:'cakes',rating:4.6,reviews:93,image:img('1544025162-d76694265947'),tags:['Specialty'],servings:'8–10 servings',allergens:['Gluten','Dairy','Eggs']},
{id:'eid-gift-box',name:'Eid Celebration Box',nameAr:'صندوق هدايا العيد',description:'Signature pastries, macarons and sweets in an elegant keepsake box.',price:18,category:'giftboxes',rating:5,reviews:201,image:img('1549465220-1a8b9238cd48'),tags:['Seasonal','Gift'],seasonal:true,gift:true,servings:'15–20 pieces',allergens:['Gluten','Dairy','Nuts']},
{id:'classic-gift-box',name:'Classic Gift Box',nameAr:'صندوق الهدايا الكلاسيكي',description:'A refined selection of One Bite favorites, ready to gift.',price:14,category:'giftboxes',rating:4.9,reviews:119,image:img('1607083206968-13611e3d76db'),tags:['Gift'],gift:true,servings:'12–16 pieces',allergens:['Gluten','Dairy','Nuts']}
];
export const reviews=[{name:'Mariam A.',text:'The chocolate truffle cake was flawless — rich, elegant and delivered exactly on time.'},{name:'Noura K.',text:'One Bite is now our family celebration tradition. The packaging is beautiful too.'},{name:'Sarah M.',text:'Fresh pastries, excellent service and the best Lotus cheesecake in Kuwait.'}];
